#!/usr/bin/env bash
# Shared implementation of the tofu recipes from .just/*.just — `just cluster plan` and co.
# Do not run directly. The .just/ directory is hidden on purpose: by hand you call `just`,
# and for things you have to do yourself there is scripts/.
#
#   tofu.sh <plan|apply> <cluster|platform|edge> [arguments for tofu]
#
# Formatting and validation are not here: `just check` does them for every layer at once.
set -euo pipefail

ACTION="${1:?missing action}"
shift
TARGET="${1:?missing target}"
shift

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF="$ROOT/terraform/$TARGET"

command -v tofu >/dev/null || {
    echo "tofu not found — it is in ~/.dotfiles/fedora/nix/home.nix, run ~/scripts/fedora/nix/apply.sh" >&2
    exit 1
}
[ -d "$TF" ] || {
    echo "no such configuration: $TF" >&2
    exit 1
}

# plan needs the providers, and those only appear after init.
[ -d "$TF/.terraform" ] || {
    echo "missing $TF/.terraform — first: (cd terraform/$TARGET && tofu init)" >&2
    exit 1
}

# cluster/ and edge/ have secrets; platform takes everything from the kubeconfig.
# Both files are generated by scripts/setup.sh from .secrets/platform.env — nobody writes them by hand.
if [ "$TARGET" != "platform" ] && [ ! -f "$TF/secrets.auto.tfvars" ]; then
    echo "missing $TF/secrets.auto.tfvars" >&2
    echo "  ./scripts/setup.sh" >&2
    exit 1
fi

# Reads an output that may not exist in the state yet. We check via -json, not
# -raw: with an empty state `output -raw` prints a warning TO STDOUT and exits zero,
# so `||` would never kick in.
output() {
    (cd "$TF" && tofu output -json "$1" >/dev/null 2>&1) || {
        printf '%s' "${2:-?}"
        return
    }
    (cd "$TF" && tofu output -raw "$1" 2>/dev/null)
}

cd "$TF"

case "$ACTION" in
    plan)
        tofu plan "$@"
        ;;

    apply)
        # The Proxmox provider uploads cloud-init and imports the disk over SSH, not the API.
        # An empty agent fails halfway through, when the machine is already being created.
        if [ "$TARGET" = "cluster" ] && ! ssh-add -l >/dev/null 2>&1; then
            echo "the SSH agent has no keys — the provider will not upload the cloud-init file" >&2
            echo "  run: ssh pve true" >&2
            exit 1
        fi

        tofu apply "$@"

        echo
        echo "== Next =="
        case "$TARGET" in
            cluster)
                cat <<MSG
  k3s keeps installing for a while after tofu finishes — cloud-init does
  its thing in the background, usually two to three minutes.

  ready:      ssh $(output vm_user maniumek)@$(output vm_ip) 'ls /var/lib/cloud/k3s-ready'
  kubectl:    just cluster kubeconfig
  watch:      k9s
MSG
                ;;
            platform)
                cat <<MSG
  Argo CD needs a moment before all pods are up.

  watch:      k9s  ->  :po  ·  :ing  ·  :applications
  password:   just argo password
  address:    $(output argocd_url "(after apply)")
MSG
                ;;
            edge)
                cat <<MSG
  The tunnel exists on the Cloudflare side, but nothing connects to it until
  cloudflared in the cluster gets the token.

  token:      ./scripts/setup.sh              (puts it into the cloudflared-token Secret)
  cloudflared: git push                       (Argo deploys it from argocd/apps/platform/)
  status:     just argo apps  ·  Zero Trust dashboard → Networks → Tunnels
  addresses:  $(cd "$TF" && tofu output -json urls 2>/dev/null | tr -d '[]"' | tr ',' ' ')
MSG
                ;;
        esac
        ;;
    *)
        echo "unknown action: $ACTION" >&2
        exit 2
        ;;
esac
