# shellcheck shell=bash
# Shared functions for the setup.sh scripts — platform and projects. Sourced, not executed:
#
#   source "$ROOT/scripts/.internal/lib.sh"
#
# Every setup.sh has the same shape: load its secrets source → ask → save the source
# → distribute (tfvars, files for edge, Secrets in the cluster). The repeated steps live here.
#
# Sources live in .secrets/ at the repo root, one file per scope (platform.env,
# automat-operat-prod.env…), outside git. Each script reads and writes ONLY its own file.

SECRETS_DIR="$ROOT/.secrets"
declare -gA CURRENT=()

# ── secrets source ────────────────────────────────────────────────────────────

# load_source NAME — .secrets/NAME.env into the CURRENT array
load_source() {
    SOURCE="$SECRETS_DIR/$1.env"
    CURRENT=()
    [ -f "$SOURCE" ] || return 0
    local k v
    while IFS='=' read -r k v; do
        [[ "$k" =~ ^[A-Z_]+$ ]] || continue
        v="${v%\"}"
        CURRENT["$k"]="${v#\"}"
    done <"$SOURCE"
}

# save_source KEY… — from the CURRENT array to the file loaded by load_source
save_source() {
    mkdir -p "$SECRETS_DIR" && chmod 700 "$SECRETS_DIR"
    (
        umask 077
        {
            echo "# Generated by setup.sh. Outside git — the only place where these values"
            echo "# are entered by hand. Edit by running the script again."
            local k
            for k in "$@"; do printf '%s="%s"\n' "$k" "${CURRENT[$k]}"; done
        } >"$SOURCE"
    )
    echo "  saved: ${SOURCE#"$ROOT"/} (600)"
}

mask() {
    local v="$1"
    [ ${#v} -le 8 ] && {
        printf '********'
        return
    }
    printf '%s…%s' "${v:0:4}" "${v: -4}"
}

# ask NAME "description" [default-if-missing] [silent]
ask() {
    local name="$1" desc="$2" fallback="${3:-}" silent="${4:-}" old="${CURRENT[$1]:-}" new=""
    echo
    echo "  $desc"
    if [ -n "$old" ]; then
        echo "  current: $(mask "$old")   [Enter = keep]"
    elif [ -n "$fallback" ]; then
        echo "  suggested: $(mask "$fallback")   [Enter = accept]"
        old="$fallback"
    else
        echo "  required — not provided yet"
    fi
    if [ -n "$silent" ]; then
        read -rsp "  > " new
        echo
    else
        read -rp "  > " new
    fi
    if [ -z "$new" ]; then
        [ -n "$old" ] || {
            echo "  this value is required" >&2
            return 1
        }
        new="$old"
    fi
    CURRENT["$name"]="$new"
}

# ── access groups for terraform/edge ──────────────────────────────────────────

# write_group NAME "a@x, b@y" — terraform/edge/access/NAME.json with a list of emails.
# terraform/edge builds the groups from all files in that directory, so each script
# adds only its own — the order in which they run does not matter.
write_group() {
    local name="$1" file="$ROOT/terraform/edge/access/$1.json" IFS=',' e json=""
    for e in $2; do
        e="${e//[[:space:]]/}"
        [ -n "$e" ] && json+="${json:+, }\"$e\""
    done
    mkdir -p "$(dirname "$file")"
    (umask 077 && printf '[%s]\n' "$json" >"$file")
    echo "  saved: ${file#"$ROOT"/}  (group \"$name\")"
}

# ── cluster ───────────────────────────────────────────────────────────────────

# cluster_available — points KUBECONFIG at this repo's file and checks that the cluster responds.
# Always our own file, not KUBECONFIG from the shell: one merged from many clusters targets
# whichever happens to be selected.
cluster_available() {
    export KUBECONFIG="$ROOT/kubeconfig"
    if ! command -v kubectl >/dev/null; then
        echo "  skipped: kubectl not found"
        return 1
    elif [ ! -f "$KUBECONFIG" ]; then
        echo "  skipped: no kubeconfig (just cluster kubeconfig)"
        return 1
    elif ! kubectl cluster-info >/dev/null 2>&1; then
        echo "  skipped: cluster unreachable (not created yet? first: just cluster apply)"
        return 1
    fi
}

# secret NAMESPACE NAME KEY=VALUE… — idempotent: creates the namespace and the Secret or
# updates them. --dry-run + apply instead of create, because a plain `create` fails when the
# object already exists. Argo also creates project namespaces (CreateNamespace), but the
# Secret needs somewhere to live before the first sync.
secret() {
    local ns="$1" name="$2"
    shift 2
    local args=() kv
    for kv in "$@"; do args+=(--from-literal="$kv"); done
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl create secret generic "$name" --namespace "$ns" "${args[@]}" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    echo "  Secret $name in namespace $ns: up to date"
}

# registry_secret NAMESPACE NAME SERVER USER TOKEN — a docker-registry Secret that
# imagePullSecrets uses when images live in a private registry (e.g. GHCR of a private
# repo). Idempotent, like `secret`.
registry_secret() {
    local ns="$1" name="$2" server="$3" user="$4" token="$5"
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl create secret docker-registry "$name" --namespace "$ns" \
        --docker-server="$server" --docker-username="$user" --docker-password="$token" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    echo "  Secret $name (registry $server) in namespace $ns: up to date"
}

# argo_repo_secret NAME URL KEY_FILE — Argo CD access to a private repo over SSH. Argo
# recognizes such Secrets by the secret-type=repository label and matches them to an
# Application by `url`, so the URL must match repoURL in argocd/apps/ character for character.
# The key is the repo's deploy key: read-only and limited to that one repo.
argo_repo_secret() {
    local name="$1" url="$2" key_file="$3"
    kubectl create secret generic "$name" --namespace argocd \
        --from-literal=type=git --from-literal=url="$url" --from-file=sshPrivateKey="$key_file" \
        --dry-run=client -o yaml |
        kubectl label --local -f - argocd.argoproj.io/secret-type=repository -o yaml |
        kubectl apply -f - >/dev/null
    echo "  Secret $name in namespace argocd (repo $url): up to date"
}
