# shellcheck shell=bash
# Shared functions for the setup.sh scripts — platform and projects. Sourced, not executed:
#
#   source "$ROOT/scripts/.internal/lib.sh"
#
# Every setup.sh has the same shape: load its secrets source → ask → save the source
# → distribute (tfvars, files for edge, Secrets in the cluster). The repeated steps live here.
#
# Sources live in .secrets/ at the repo root, one file per scope (platform.env,
# automat-operat-prod.env…), outside git. Each script reads and writes ONLY its own file.

SECRETS_DIR="$ROOT/.secrets"
declare -gA CURRENT=()

# ── secrets source ────────────────────────────────────────────────────────────

# load_source NAME — .secrets/NAME.env into the CURRENT array
load_source() {
    SOURCE="$SECRETS_DIR/$1.env"
    CURRENT=()
    [ -f "$SOURCE" ] || return 0
    local k v
    while IFS='=' read -r k v; do
        [[ "$k" =~ ^[A-Z_]+$ ]] || continue
        v="${v%\"}"
        CURRENT["$k"]="${v#\"}"
    done <"$SOURCE"
}

# save_source KEY… — from the CURRENT array to the file loaded by load_source
save_source() {
    mkdir -p "$SECRETS_DIR" && chmod 700 "$SECRETS_DIR"
    (
        umask 077
        {
            echo "# Generated by setup.sh. Outside git — the only place where these values"
            echo "# are entered by hand. Edit by running the script again."
            local k
            for k in "$@"; do printf '%s="%s"\n' "$k" "${CURRENT[$k]}"; done
        } >"$SOURCE"
    )
    echo "  saved: ${SOURCE#"$ROOT"/} (600)"
}

mask() {
    local v="$1"
    [ ${#v} -le 8 ] && {
        printf '********'
        return
    }
    printf '%s…%s' "${v:0:4}" "${v: -4}"
}

# ask NAME "description" [default-if-missing] [silent]
ask() {
    local name="$1" desc="$2" fallback="${3:-}" silent="${4:-}" old="${CURRENT[$1]:-}" new=""
    echo
    echo "  $desc"
    if [ -n "$old" ]; then
        echo "  current: $(mask "$old")   [Enter = keep]"
    elif [ -n "$fallback" ]; then
        echo "  suggested: $(mask "$fallback")   [Enter = accept]"
        old="$fallback"
    else
        echo "  required — not provided yet"
    fi
    if [ -n "$silent" ]; then
        read -rsp "  > " new
        echo
    else
        read -rp "  > " new
    fi
    if [ -z "$new" ]; then
        [ -n "$old" ] || {
            echo "  this value is required" >&2
            return 1
        }
        new="$old"
    fi
    CURRENT["$name"]="$new"
}

# ── access groups for terraform/edge ──────────────────────────────────────────

# write_group NAME "a@x, b@y" — terraform/edge/access/NAME.json with a list of emails.
# terraform/edge builds the groups from all files in that directory, so each script
# adds only its own — the order in which they run does not matter.
write_group() {
    local name="$1" file="$ROOT/terraform/edge/access/$1.json" IFS=',' e json=""
    for e in $2; do
        e="${e//[[:space:]]/}"
        [ -n "$e" ] && json+="${json:+, }\"$e\""
    done
    mkdir -p "$(dirname "$file")"
    (umask 077 && printf '[%s]\n' "$json" >"$file")
    echo "  saved: ${file#"$ROOT"/}  (group \"$name\")"
}

# ── cluster ───────────────────────────────────────────────────────────────────

# cluster_available — points KUBECONFIG at this repo's file and checks that the cluster responds.
# Always our own file, not KUBECONFIG from the shell: one merged from many clusters targets
# whichever happens to be selected.
cluster_available() {
    export KUBECONFIG="$ROOT/kubeconfig"
    if ! command -v kubectl >/dev/null; then
        echo "  skipped: kubectl not found"
        return 1
    elif [ ! -f "$KUBECONFIG" ]; then
        echo "  skipped: no kubeconfig (just cluster kubeconfig)"
        return 1
    elif ! kubectl cluster-info >/dev/null 2>&1; then
        echo "  skipped: cluster unreachable (not created yet? first: just cluster apply)"
        return 1
    fi
}

# secret_key NAMESPACE NAME KEY VALUE — sets ONE key of a Secret several scripts share, leaving
# the keys the other scripts wrote alone (secret() below replaces the whole Secret). The value
# travels through stdin, never as an argument.
secret_key() {
    local ns="$1" name="$2" key="$3" value="$4"
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl -n "$ns" get secret "$name" >/dev/null 2>&1 || kubectl -n "$ns" create secret generic "$name" >/dev/null
    printf '%s' "$value" | jq -Rs --arg k "$key" '{stringData: {($k): .}}' |
        kubectl -n "$ns" patch secret "$name" --type merge --patch-file /dev/stdin >/dev/null
    echo "  Secret $name, key $key, in namespace $ns: up to date"
}

# discord_check CHANNEL URL — is this a working Discord webhook, and is it the right channel?
# Checks the form, asks Discord whether the webhook exists (GET: no message), then posts one
# short message to the channel so you see it land where it should. The URL holds the webhook's
# token, so it reaches curl through stdin (-K -), never as an argument.
discord_check() {
    local channel="$1" url="$2" code
    if ! [[ "$url" =~ ^https://(discord\.com|discordapp\.com)/api/webhooks/[0-9]+/[A-Za-z0-9_-]+$ ]]; then
        echo "  #$channel: not a Discord webhook URL (https://discord.com/api/webhooks/<id>/<token>) — not saved to the cluster" >&2
        return 1
    fi
    code="$(printf 'url = "%s"\n' "$url" | curl -s -o /dev/null -w '%{http_code}' -K -)"
    if [ "$code" != 200 ]; then
        echo "  #$channel: Discord does not know this webhook (HTTP $code — deleted, or a typo) — not saved to the cluster" >&2
        return 1
    fi
    code="$(printf 'url = "%s"\n' "$url" |
        curl -s -o /dev/null -w '%{http_code}' -K - -H 'Content-Type: application/json' \
            -d "{\"content\": \":bell: #$channel podłączony do suwalski-platform (setup.sh). Tu będą przychodzić alerty.\"}")"
    if [ "$code" != 204 ] && [ "$code" != 200 ]; then
        echo "  #$channel: the test message was refused (HTTP $code)" >&2
        return 1
    fi
    echo "  #$channel: webhook works — a test message is on the channel; check it is the right one"
}

# discord_channel CHANNEL URL — where the alerts of one Discord channel go. CHANNEL is the
# channel's name on Discord (suw-platf-notif, app-automat-operat-dev-notif, …): Argo CD
# Notifications knows it as service <CHANNEL> with the URL in key discord-<CHANNEL>
# (terraform/platform/notifications.tf), Gatus as variable DISCORD_<CHANNEL>
# (argocd/manifests/gatus/). URL "off" = no channel.
discord_channel() {
    local channel="$1" url="$2" var
    if [ "$url" = off ]; then
        echo "  skipped: Discord channel #$channel (off)"
        return 0
    fi
    # A bad URL is reported and skipped — the rest of setup.sh still runs; enter it again next run.
    discord_check "$channel" "$url" || return 0
    var="DISCORD_$(printf '%s' "$channel" | tr 'a-z-' 'A-Z_')"
    secret_key argocd argocd-notifications-secret "discord-$channel" "$url"
    secret_key gatus gatus-discord "$var" "$url"
    # Gatus reads its variables at start-up.
    kubectl -n gatus rollout restart deployment/gatus >/dev/null 2>&1 || true
}

# argocd_account_token ACCOUNT — prints a new API token for a local Argo CD account (one with
# the apiKey capability, terraform/platform/main.tf). Logs in as admin with the initial password
# through a short port-forward; passwords and tokens travel through stdin, never as arguments.
argocd_account_token() {
    local account="$1" pf session token
    kubectl -n argocd port-forward svc/argocd-server 18089:80 >/dev/null 2>&1 &
    pf=$!
    for _ in $(seq 1 20); do
        curl -fs -o /dev/null http://127.0.0.1:18089/healthz && break
        sleep 0.5
    done
    session="$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d |
        jq -Rn '{username: "admin", password: input}' |
        curl -fs -H 'content-type: application/json' -d @- http://127.0.0.1:18089/api/v1/session | jq -r '.token // empty')" || true
    if [ -n "$session" ]; then
        token="$(printf 'header = "Authorization: Bearer %s"\n' "$session" |
            curl -fs -K - -X POST -H 'content-type: application/json' -d '{}' \
                "http://127.0.0.1:18089/api/v1/account/$account/token" | jq -r '.token // empty')" || true
    fi
    kill "$pf" 2>/dev/null || true
    printf '%s' "${token:-}"
}

# proxmox_readonly_token NAME — creates (or re-creates) the API token root@pam!NAME with the
# read-only PVEAuditor role and prints "root@pam!NAME=<secret>". Proxmox shows a token's secret
# only once, so the caller saves it. Uses the Terraform token (CURRENT[PROXMOX_API_TOKEN]).
proxmox_readonly_token() {
    local name="$1" api="https://192.168.0.111:8006/api2/json" auth value
    auth="$(printf 'header = "Authorization: PVEAPIToken=%s"\n' "${CURRENT[PROXMOX_API_TOKEN]}")"
    printf '%s' "$auth" | curl -sk -K - -X DELETE "$api/access/users/root@pam/token/$name" >/dev/null || true
    value="$(printf '%s' "$auth" | curl -sk -K - -X POST -d privsep=1 -d "comment=Homepage widget (read-only)" \
        "$api/access/users/root@pam/token/$name" | jq -r '.data.value // empty')"
    [ -n "$value" ] || return 1
    printf '%s' "$auth" | curl -sk -K - -X PUT -d path=/ -d roles=PVEAuditor -d "tokens=root@pam!$name" \
        "$api/access/acl" >/dev/null
    printf 'root@pam!%s=%s' "$name" "$value"
}

# secret NAMESPACE NAME KEY=VALUE… — idempotent: creates the namespace and the Secret or
# updates them. --dry-run + apply instead of create, because a plain `create` fails when the
# object already exists. Argo also creates project namespaces (CreateNamespace), but the
# Secret needs somewhere to live before the first sync.
secret() {
    local ns="$1" name="$2"
    shift 2
    local args=() kv
    for kv in "$@"; do args+=(--from-literal="$kv"); done
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl create secret generic "$name" --namespace "$ns" "${args[@]}" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    echo "  Secret $name in namespace $ns: up to date"
}

# registry_secret NAMESPACE NAME SERVER USER TOKEN — a docker-registry Secret that
# imagePullSecrets uses when images live in a private registry (e.g. GHCR of a private
# repo). Idempotent, like `secret`.
registry_secret() {
    local ns="$1" name="$2" server="$3" user="$4" token="$5"
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl create secret docker-registry "$name" --namespace "$ns" \
        --docker-server="$server" --docker-username="$user" --docker-password="$token" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    echo "  Secret $name (registry $server) in namespace $ns: up to date"
}

# argo_repo_secret NAME URL KEY_FILE — Argo CD access to a private repo over SSH. Argo
# recognizes such Secrets by the secret-type=repository label and matches them to an
# Application by `url`, so the URL must match repoURL in argocd/apps/ character for character.
# The key is the repo's deploy key: read-only and limited to that one repo.
argo_repo_secret() {
    local name="$1" url="$2" key_file="$3"
    kubectl create secret generic "$name" --namespace argocd \
        --from-literal=type=git --from-literal=url="$url" --from-file=sshPrivateKey="$key_file" \
        --dry-run=client -o yaml |
        kubectl label --local -f - argocd.argoproj.io/secret-type=repository -o yaml |
        kubectl apply -f - >/dev/null
    echo "  Secret $name in namespace argocd (repo $url): up to date"
}

# database_access NAMESPACE ROLE — the project's login to the shared PostgreSQL
# (argocd/manifests/postgres). The password is generated once and nobody types it: it lives
# in the Secret <ROLE with dashes> in namespace postgres, which the Cluster's managed role
# reads, and the project gets it as DATABASE_URL in its Secret "database". The database has
# the role's name. Values go through stdin, never the process list.
database_access() {
    local ns="$1" role="$2" secret="${2//_/-}" password
    kubectl create namespace postgres --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    if kubectl -n postgres get secret "$secret" >/dev/null 2>&1; then
        echo "  Secret $secret in namespace postgres: present (password kept)"
    else
        openssl rand -hex 24 | tr -d '\n' |
            kubectl -n postgres create secret generic "$secret" --type=kubernetes.io/basic-auth \
                --from-literal=username="$role" --from-file=password=/dev/stdin >/dev/null
        # Tells CloudNativePG to re-read the Secret when it changes.
        kubectl -n postgres label secret "$secret" cnpg.io/reload=true >/dev/null
        echo "  Secret $secret in namespace postgres: created with a new password"
    fi
    password="$(kubectl -n postgres get secret "$secret" -o jsonpath='{.data.password}' | base64 -d)"
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    printf 'DATABASE_URL=postgresql://%s:%s@shared-rw.postgres.svc:5432/%s\n' "$role" "$password" "$role" |
        kubectl -n "$ns" create secret generic database --from-env-file=/dev/stdin --dry-run=client -o yaml |
        kubectl apply -f - >/dev/null
    echo "  Secret database (DATABASE_URL) in namespace $ns: up to date"
}

# access_config NAMESPACE APP — what an app's backend needs to verify the Cloudflare Access
# login token: the team domain (token issuer and signing keys) and the app's audience tag.
# Both are terraform/edge outputs, so this runs after `just edge apply`; nothing is secret,
# hence a ConfigMap, "cloudflare-access".
access_config() {
    local ns="$1" app="$2" team aud
    team="$(tofu -chdir="$ROOT/terraform/edge" output -raw access_team_domain 2>/dev/null)" || {
        echo "  skipped cloudflare-access: no terraform/edge outputs yet (just edge apply)"
        return 0
    }
    aud="$(tofu -chdir="$ROOT/terraform/edge" output -json access_aud | jq -r --arg app "$app" '.[$app] // empty')"
    [ -n "$aud" ] || {
        echo "  skipped cloudflare-access: no Access application \"$app\" in terraform/edge (edge.auto.tfvars → apps)"
        return 0
    }
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl -n "$ns" create configmap cloudflare-access \
        --from-literal=CF_ACCESS_TEAM_DOMAIN="$team" --from-literal=CF_ACCESS_AUD="$aud" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    echo "  ConfigMap cloudflare-access in namespace $ns: up to date"
}
