#!/usr/bin/env bash
# PLATFORM setup on a freshly cloned repo. Idempotent — run it as often as you like.
#
# Steps: tools (just) → platform secrets → distributing them.
#
# Only what is shared by the whole cluster. Project secrets (emails of people with access,
# application passwords) have their own scripts in scripts/projects/<project>/[<env>/]setup.sh —
# this script does not touch them.
#
#   .secrets/platform.env ──┬──>  terraform/cluster/secrets.auto.tfvars   (Proxmox, SSH, state passphrase)
#                           ├──>  terraform/edge/secrets.auto.tfvars      (Cloudflare token, state passphrase)
#                           ├──>  terraform/platform/secrets.auto.tfvars  (state passphrase)
#                           ├──>  terraform/edge/access/admin.json        (group "admin": you)
#                           └──>  Secret cloudflared-token in the cluster*
#
#   * the tunnel token does not come from .secrets/ but from the terraform/edge output — it is
#     created by `just edge apply`. That is why you run this script again after the first edge apply.
#
# ⚠ Temporary. Eventually the secrets should live in git, encrypted — see TODO.md.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/scripts/.internal/lib.sh"

# ── tools ─────────────────────────────────────────────────────────────────────
# First, because everything after setup goes through `just`. Missing just does not block
# the secrets — we distribute them anyway, and the warning stays on screen.
echo "== Tools =="
"$ROOT/scripts/.internal/install-just.sh" ||
    echo "  warning: without just no \`just ...\` will work — distributing the secrets anyway" >&2

# Hooks versioned in .githooks/ (gitleaks before every commit — the repo is public).
git -C "$ROOT" config core.hooksPath .githooks
echo "  git hooks: .githooks/ (gitleaks before every commit)"

# ── platform secrets ──────────────────────────────────────────────────────────
echo
echo "== Platform secrets =="
load_source platform
echo "  source: ${SOURCE#"$ROOT"/}"

ask PROXMOX_API_TOKEN \
    "Proxmox API token (root@pam!name=UUID). Create it with: ssh pve 'pveum user token add root@pam terraform --privsep 0'" \
    "" silent

_key=""
[ -f "$HOME/.ssh/id_ed25519.pub" ] && _key="$(cat "$HOME/.ssh/id_ed25519.pub")"
ask SSH_PUBLIC_KEY \
    "Public key allowed onto the k3s machine" \
    "$_key"

ask CLOUDFLARE_API_TOKEN \
    "Cloudflare API token for terraform/edge. Permissions: docs/edge/guide/edge-4-sekrety.md" \
    "" silent

ask ACCESS_ADMIN \
    "Your email — the 'admin' group in Cloudflare Access (things only for you, e.g. dev environments)" \
    ""

# Encrypts the Terraform state of every layer (terraform/*/encryption.tf). Generated once,
# never typed: Enter accepts the random one. Losing it makes the encrypted state unreadable.
ask STATE_PASSPHRASE \
    "Passphrase encrypting the Terraform state. KEEP A COPY in a password manager — the state in git is useless without it" \
    "$(openssl rand -base64 33 | tr -d '\n')" silent

# Alerts go to Discord, one channel per concern. The platform owns two; every project
# environment owns its own (its setup.sh). Discord: channel settings → Integrations → Webhooks →
# New Webhook → Copy Webhook URL. Whoever has a URL can post to the channel, so it is a secret.
ask DISCORD_SUW_PLATF_NOTIF \
    "Discord webhook of #suw-platf-notif — the platform is down (tunnel, database, platform apps). Enter = off" \
    "off" silent
ask DISCORD_SUW_PLATF_DEPLOYMENTS_NOTIF \
    "Discord webhook of #suw-platf-deployments-notif — '✅ deployed' from every environment. Enter = off" \
    "off" silent

echo
save_source PROXMOX_API_TOKEN SSH_PUBLIC_KEY CLOUDFLARE_API_TOKEN ACCESS_ADMIN STATE_PASSPHRASE \
    DISCORD_SUW_PLATF_NOTIF DISCORD_SUW_PLATF_DEPLOYMENTS_NOTIF

# ── distribution: terraform/cluster ───────────────────────────────────────────
echo
echo "== terraform/cluster =="
TFV="$ROOT/terraform/cluster/secrets.auto.tfvars"
(
    umask 077
    {
        echo "# GENERATED by scripts/setup.sh — do not edit by hand."
        echo "# The source is .secrets/platform.env."
        echo
        printf 'proxmox_api_token = "%s"\n\n' "${CURRENT[PROXMOX_API_TOKEN]}"
        printf 'ssh_public_keys = [\n  "%s",\n]\n\n' "${CURRENT[SSH_PUBLIC_KEY]}"
        printf 'state_passphrase = "%s"\n' "${CURRENT[STATE_PASSPHRASE]}"
    } >"$TFV"
)
echo "  saved: ${TFV#"$ROOT"/}"

# ── distribution: terraform/edge ──────────────────────────────────────────────
echo
echo "== terraform/edge =="
TFV="$ROOT/terraform/edge/secrets.auto.tfvars"
(
    umask 077
    {
        echo "# GENERATED by scripts/setup.sh — do not edit by hand."
        echo "# The source is .secrets/platform.env. Access groups are in access/*.json."
        echo
        printf 'cloudflare_api_token = "%s"\n\n' "${CURRENT[CLOUDFLARE_API_TOKEN]}"
        printf 'state_passphrase = "%s"\n' "${CURRENT[STATE_PASSPHRASE]}"
    } >"$TFV"
)
echo "  saved: ${TFV#"$ROOT"/}"
write_group admin "${CURRENT[ACCESS_ADMIN]}"

# ── distribution: terraform/platform ──────────────────────────────────────────
echo
echo "== terraform/platform =="
TFV="$ROOT/terraform/platform/secrets.auto.tfvars"
(
    umask 077
    {
        echo "# GENERATED by scripts/setup.sh — do not edit by hand."
        echo "# The source is .secrets/platform.env. The rest of this layer comes from the kubeconfig."
        echo
        printf 'state_passphrase = "%s"\n' "${CURRENT[STATE_PASSPHRASE]}"
    } >"$TFV"
)
echo "  saved: ${TFV#"$ROOT"/}"

# ── distribution: cluster ─────────────────────────────────────────────────────
echo
echo "== cluster =="
if cluster_available; then
    # Tunnel token: from the terraform/edge output, not from .secrets/ — created by edge apply.
    # We check via -json: with an empty state `output -raw` prints a warning to stdout
    # and exits zero, so the warning text would end up in the Secret.
    EDGE="$ROOT/terraform/edge"
    if [ -d "$EDGE/.terraform" ] && (cd "$EDGE" && tofu output -json tunnel_token >/dev/null 2>&1); then
        secret cloudflared cloudflared-token "token=$(cd "$EDGE" && tofu output -raw tunnel_token)"
    else
        echo "  skipped: tunnel token (no tunnel yet — first: just edge apply)"
    fi

    # Alerts (terraform/platform/notifications.tf, argocd/manifests/gatus/). WHICH events go to
    # which channel is decided in git; this only says where each channel is.
    discord_channel suw-platf-notif "${CURRENT[DISCORD_SUW_PLATF_NOTIF]}"
    discord_channel suw-platf-deployments-notif "${CURRENT[DISCORD_SUW_PLATF_DEPLOYMENTS_NOTIF]}"
fi

echo
echo "== Next =="
echo "  projects:  scripts/projects/<project>/[<env>/]setup.sh — each with its own secrets"
echo "  init:      (cd terraform/<cluster|platform|edge> && tofu init)   # if not done yet"
echo "  then:      just"
