#!/usr/bin/env bash
# PLATFORM setup on a freshly cloned repo. Idempotent — run it as often as you like.
#
# Steps: tools (just) → platform secrets → distributing them.
#
# Only what is shared by the whole cluster. Project secrets (emails of people with access,
# application passwords) have their own scripts in scripts/projects/<project>/[<env>/]setup.sh —
# this script does not touch them.
#
#   .secrets/platform.env ──┬──>  terraform/cluster/secrets.auto.tfvars   (Proxmox, SSH)
#                           ├──>  terraform/edge/secrets.auto.tfvars      (Cloudflare token)
#                           ├──>  terraform/edge/access/admin.json        (group "admin": you)
#                           └──>  Secret cloudflared-token in the cluster*
#
#   * the tunnel token does not come from .secrets/ but from the terraform/edge output — it is
#     created by `just edge apply`. That is why you run this script again after the first edge apply.
#
# ⚠ Temporary. Eventually the secrets should live in git, encrypted — see TODO.md.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/scripts/.internal/lib.sh"

# ── tools ─────────────────────────────────────────────────────────────────────
# First, because everything after setup goes through `just`. Missing just does not block
# the secrets — we distribute them anyway, and the warning stays on screen.
echo "== Tools =="
"$ROOT/scripts/.internal/install-just.sh" ||
    echo "  warning: without just no \`just ...\` will work — distributing the secrets anyway" >&2

# ── platform secrets ──────────────────────────────────────────────────────────
echo
echo "== Platform secrets =="
load_source platform
echo "  source: ${SOURCE#"$ROOT"/}"

ask PROXMOX_API_TOKEN \
    "Proxmox API token (root@pam!name=UUID). Create it with: ssh pve 'pveum user token add root@pam terraform --privsep 0'" \
    "" silent

_key=""
[ -f "$HOME/.ssh/id_ed25519.pub" ] && _key="$(cat "$HOME/.ssh/id_ed25519.pub")"
ask SSH_PUBLIC_KEY \
    "Public key allowed onto the k3s machine" \
    "$_key"

ask CLOUDFLARE_API_TOKEN \
    "Cloudflare API token for terraform/edge. Permissions: docs/edge/guide/edge-4-sekrety.md" \
    "" silent

ask ACCESS_ADMIN \
    "Your email — the 'admin' group in Cloudflare Access (things only for you, e.g. dev environments)" \
    ""

echo
save_source PROXMOX_API_TOKEN SSH_PUBLIC_KEY CLOUDFLARE_API_TOKEN ACCESS_ADMIN

# ── distribution: terraform/cluster ───────────────────────────────────────────
echo
echo "== terraform/cluster =="
TFV="$ROOT/terraform/cluster/secrets.auto.tfvars"
(
    umask 077
    {
        echo "# GENERATED by scripts/setup.sh — do not edit by hand."
        echo "# The source is .secrets/platform.env."
        echo
        printf 'proxmox_api_token = "%s"\n\n' "${CURRENT[PROXMOX_API_TOKEN]}"
        printf 'ssh_public_keys = [\n  "%s",\n]\n' "${CURRENT[SSH_PUBLIC_KEY]}"
    } >"$TFV"
)
echo "  saved: ${TFV#"$ROOT"/}"

# ── distribution: terraform/edge ──────────────────────────────────────────────
echo
echo "== terraform/edge =="
TFV="$ROOT/terraform/edge/secrets.auto.tfvars"
(
    umask 077
    {
        echo "# GENERATED by scripts/setup.sh — do not edit by hand."
        echo "# The source is .secrets/platform.env. Access groups are in access/*.json."
        echo
        printf 'cloudflare_api_token = "%s"\n' "${CURRENT[CLOUDFLARE_API_TOKEN]}"
    } >"$TFV"
)
echo "  saved: ${TFV#"$ROOT"/}"
write_group admin "${CURRENT[ACCESS_ADMIN]}"

# ── distribution: cluster ─────────────────────────────────────────────────────
echo
echo "== cluster =="
if cluster_available; then
    # Tunnel token: from the terraform/edge output, not from .secrets/ — created by edge apply.
    # We check via -json: with an empty state `output -raw` prints a warning to stdout
    # and exits zero, so the warning text would end up in the Secret.
    EDGE="$ROOT/terraform/edge"
    if [ -d "$EDGE/.terraform" ] && (cd "$EDGE" && tofu output -json tunnel_token >/dev/null 2>&1); then
        secret cloudflared cloudflared-token "token=$(cd "$EDGE" && tofu output -raw tunnel_token)"
    else
        echo "  skipped: tunnel token (no tunnel yet — first: just edge apply)"
    fi
fi

echo
echo "== Next =="
echo "  projects:  scripts/projects/<project>/[<env>/]setup.sh — each with its own secrets"
echo "  init:      (cd terraform/<cluster|platform|edge> && tofu init)   # if not done yet"
echo "  then:      just"
