# Split of values — the same as in cluster/:
#
#   default here         — design decisions: where the tunnel sends traffic, how long a session lasts
#   edge.auto.tfvars     — facts about the Cloudflare account and the list of applications (in git)
#   secrets.auto.tfvars  — API token (outside git, generated by scripts/setup.sh)
#   access/*.json        — EMAILS of people in groups (outside git, see access.tf)
#
# Emails are not secret like a password, but they are private: the repo is public, and auntie's
# address must never end up in it. That is why git holds only the NAME of the group an application
# admits, and who belongs to it lives in access/, outside git.

# ── Cloudflare account: depends on the environment ───────────────────────────

variable "account_id" {
  description = "Cloudflare account ID (dashboard, right column). Not a secret. → edge.auto.tfvars"
  type        = string

  validation {
    condition     = can(regex("^[0-9a-f]{32}$", var.account_id))
    error_message = "account_id is 32 hex characters — copy it from the Cloudflare dashboard."
  }
}

variable "zone_name" {
  description = "Cloudflare domain the applications live under. → edge.auto.tfvars"
  type        = string
}

variable "team_name" {
  description = "Zero Trust team name, chosen at signup (from the <team>.cloudflareaccess.com address). cloudflared uses it to check Access tokens. → edge.auto.tfvars"
  type        = string
}

# ── What we expose ────────────────────────────────────────────────────────────

variable "apps" {
  description = "Applications exposed to the world: key = subdomain, access = group name (file access/<group>.json). → edge.auto.tfvars"
  type = map(object({
    access = string
  }))

  validation {
    condition     = alltrue([for k in keys(var.apps) : can(regex("^[a-z0-9-]+$", k))])
    error_message = "The application key is just the subdomain, e.g. \"automat-operat-dev\" — no dots and no domain."
  }
}

# ── Secrets ───────────────────────────────────────────────────────────────────

variable "cloudflare_api_token" {
  description = "Cloudflare API token with this layer's permissions. → secrets.auto.tfvars"
  type        = string
  sensitive   = true
}

# ── Design decisions: the same everywhere ────────────────────────────────────

variable "tunnel_name" {
  description = "Tunnel name in the Zero Trust dashboard. One tunnel per cluster."
  type        = string
  default     = "homelab"
}

variable "origin_service" {
  description = "Where cloudflared sends traffic. Traefik from k3s — it routes it by host according to Ingresses, just like on the home network."
  type        = string
  default     = "http://traefik.kube-system.svc.cluster.local:80"
}

variable "session_duration" {
  description = "How long after entering the code you do not have to log in again. 720h = 30 days: auntie enters a code roughly once a month."
  type        = string
  default     = "720h"
}
